name: exercicio2

on:
  push:
    branches: [ main ]

env:
  ARTIFACT_VAR: "File"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{env.NameFile}}
        path: .
        if-no-files-found: error
